import turtle
turtle.setup(400, 400)
turtle.speed(10)
# Draw the face
turtle.penup()
turtle.goto(0, -100)
turtle.pendown()
turtle.circle(100)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.right(90)
turtle.forward(50)
turtle.penup()
turtle.goto(-40, 20)
turtle.pendown()
turtle.dot(5)
turtle.penup()
turtle.goto(40, 20)
turtle.pendown()
turtle.dot(5)
# Draw the mouth
turtle.penup()
turtle.goto(-50, -60)
turtle.pendown()
turtle.left(90)
turtle.forward(110)
turtle.penup()
turtle.goto(-60, 60)
turtle.pendown()
# turtle.left(90)
turtle.forward(40)
turtle.penup()
turtle.goto(20, 60)
turtle.pendown()
turtle.forward(40)
turtle.done()
