import pandas as pd
data=pd.read_csv('stud.csv')
print("First 5")
first_five=data.head(2)
print(first_five)
avg_age=data['Age'].mean()
sum_age=data['Age'].sum()
print("AVG: ",avg_age)
print("Sum: ",sum_age)
min_values=data['Age'].min()
sorted=data.sort_values('Name')
print(sorted)
print(min_values)